# Generated by Django 4.2.5 on 2023-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_slide_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='description',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
