# Generated by Django 4.2.5 on 2023-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_siteicon_remove_footer_icons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='icons',
            field=models.ManyToManyField(blank=True, related_name='footer_icons', to='api.siteicon'),
        ),
        migrations.AlterField(
            model_name='header',
            name='icons',
            field=models.ManyToManyField(blank=True, related_name='header_icons', to='api.siteicon'),
        ),
    ]
