# Generated by Django 4.2.5 on 2023-09-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_footer_options_alter_footer_icons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='name',
        ),
    ]
